// 自動生成されたコードです。変更しないでください。
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "plane0":return img`
..ccc.........ffffff....
..f4cc.......fcc22ff....
..f44cc...fffccccff.....
..f244cccc22224442cc....
..f224cc2222222244b9c...
..cf2222222222222b999c..
.c22c222222222b11199b2c.
f22ccccccc222299111b222c
fffffcc222c222222222222f
.....f2222442222222222f.
....f222244fc2222222ff..
...c222244ffffffffff....
...c2222cfffc2f.........
...ffffffff2ccf.........
.......ffff2cf..........
........fffff...........
`;
            case "image2":
            case "skellyWalkLeft1":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbfff.f......
..........ffffffff......
............fffff.......
........................
........................
........................
........................
`;
            case "image3":
            case "firework2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . 3 1 1 3 . . . . . . 
. . . . . 2 1 1 1 1 2 . . . . . 
. . . . . 2 1 1 1 1 2 . . . . . 
. . . . . . 3 1 1 3 . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// 自動生成されたコードです。変更しないでください。
